# Generated by Django 4.2.16 on 2024-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehosp_app', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
